# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob nomatch notify
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall

PLATFORM=`uname -s`

if [ $PLATFORM = "Darwin" ]; then
    zstyle :compinstall filename '/Users/plengarov/.zshrc'
elif [ $PALTFORM = "Linux" ]; then
    zstyle :compinstall filename '/home/plengarov/.zshrc'
fi

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Oh-my-zsh config
if [ $PLATFORM = "Darwin" ]; then
    export ZSH="/Users/plengarov/.oh-my-zsh"
elif [ $PALTFORM = "Linux" ]; then
    export ZSH="/home/plengarov/.oh-my-zsh"
fi

plugins=(
    git
    docker
    dnf
    lein
    z
)

source $ZSH/oh-my-zsh.sh
# End of Oh-my-zsh config

# Custom config
PROMPT='[%n@%m %~]$ '

alias la='ls -la'
alias ll='ls -l'
alias e='emacsclient -t'
alias ke="emacsclient -e '(kill-emacs)'"

bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward
# End of custom config
